# Generated by Django 4.0.4 on 2022-05-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slavaukraine', '0002_topicmessage_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='description',
            field=models.CharField(max_length=150, verbose_name='Descrição'),
        ),
    ]
