# Generated by Django 4.0.4 on 2022-05-12 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slavaukraine', '0004_alter_city_country_alter_city_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertise',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Especialidade'),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Voluntário'),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slavaukraine.proposal', verbose_name='Proposta'),
        ),
    ]
